base_model = (;
    R = 70,
    w = 0,
    d = 0,
    Δ0 = 0.23,
    ξd = 70,
    a0 = 5,
    preα = 0,
    g = 0,
    α = 0,
    μ = 0,
    τΓ = 1,
    Vexponent = 2,
    Vmin = 0,
    Vmax = 0,
    ishollow = true,
)
models = Dict(
    "HCA" => (;
        base_model...,
        μ = 0.75,
        α = 85,
    ),
    "TCM_40" => (;
        base_model...,
        w = 40,
        d = 10,
        μ = 6.7,
        α = 20,
        τΓ = 48,
        g = 10,
        ishollow = false,
    ),
    "TCM_20" => (;
        base_model...,
        w = 20,
        d = 10,
        τΓ = 10,
        μ = 18.1,
        α = 50,
        g = 10,
        ishollow = false,
    ),
    "SCM" => (;
        base_model...,
        w = 70,
        d = 10,
        Vmin = -30,
        g = 10,
        τΓ = 40,
        μ = 2,
        preα = 46.66,
        ishollow = false,
    ),
    "HCA_small" => (;
        base_model...,
        R = 45,
        μ = 0.75,
        α = 40,
    ),
    "TCM_small_40" => (;
        base_model...,
        R = 45,
        w = 40,
        d = 10,
        μ = 6.7,
        α = 20,
        τΓ = 48,
        g = 10,
        ishollow = false,
    ),
    "TCM_small_20" => (;
        base_model...,
        R = 45,
        w = 20,
        d = 10,
        τΓ = 10,
        μ = 18.1,
        α = 50,
        g = 10,
        ishollow = false,
    ),
    "SCM_small" => (;
        base_model...,
        R = 45,
        w = 70,
        d = 10,
        Vmin = -30,
        g = 10,
        τΓ = 40,
        μ = 2,
        preα = 46.66,
        ishollow = false,
    ),
)